// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AbnormalTraffic: typeof import('./src/components/AbnormalTraffic/index.vue')['default']
    AutoScrollTable: typeof import('./src/components/AutoScrollTable/index.vue')['default']
    Category: typeof import('./src/components/Category/index.vue')['default']
    Container: typeof import('./src/components/Container/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    Header: typeof import('./src/components/Header/index.vue')['default']
    HistoryClass: typeof import('./src/components/HistoryClass/index.vue')['default']
    List: typeof import('./src/components/List/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    Prediction: typeof import('./src/components/Prediction/index.vue')['default']
    RealTimeClass: typeof import('./src/components/RealTimeClass/index.vue')['default']
    VueCountTo: typeof import('./src/components/VueCountTo/vue-countTo.vue')['default']
  }
}

export { }
